### ISSUE TITLE
Shader problems on Os X

### ISSUE THREAD

**Issue by kabukunz** [ratcave/ratcave#25] opened 2018-06-04 11:12 UTC
Hello
When I get to this tutorial (http://ratcave.readthedocs.io/en/latest/tutorial1.html#drawing-the-scene), I stumble into this error:

```
b"ERROR: 0:1: '' :  version '150' is not supported\nWARNING: 0:2: extension 'GL_ARB_explicit_attrib_location' is not supported\nERROR: 0:4: 'layout' : syntax error: syntax error\n"
b"ERROR: 0:1: '' :  version '150' is not supported\nWARNING: 0:2: extension 'GL_NV_shadow_samplers_cube' is not supported\n"
Traceback (most recent call last):
  File "ratc.py", line 26, in <module>
    pyglet.app.run()
  File "/Users/max/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pyglet/app/__init__.py", line 138, in run
    event_loop.run()
  File "/Users/max/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pyglet/app/base.py", line 142, in run
    self._run()
  File "/Users/max/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pyglet/app/base.py", line 154, in _run
    timeout = self.idle()
  File "/Users/max/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pyglet/app/base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "/Users/max/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "/Users/max/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pyglet/event.py", line 357, in dispatch_event
    if handler(*args):
  File "ratc.py", line 24, in on_draw
    scene.draw()
  File "/Users/max/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ratcave/scene.py", line 78, in draw
    mesh.draw()
  File "/Users/max/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ratcave/mesh.py", line 174, in draw
    self.vao = VAO(indices=self.array_indices)
  File "/Users/max/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ratcave/vertex.py", line 25, in __init__
    self.id = create_opengl_object(gl.glGenVertexArrays)
  File "/Users/max/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ratcave/utils/gl.py", line 15, in create_opengl_object
    gl_gen_function(n, byref(handle))  # Create n Empty Objects
  File "/Users/max/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pyglet/gl/lib.py", line 105, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'

```
Looks like a shader problem
I'm using Os X 10.13.3, python 3.6.2
What can I do? Thx

**Comment by nickdelgrosso** [comment] 2018-06-06 11:48
Hi,
This occurs when the default OpenGL version selected by the graphics drivers are less than version 3.2.  It occurs with Macs and with machines with only Intel graphics cards.  Because of ratcave's modular nature, it is challenging to find a good place to select and OpenGL version from within ratcave.

To deal with this, we've decreased the minimum-required version of OpenGL to one that will work on all computers.  (commit c4f2f23fdd5992576b2c9c355712816b729849b4) This can be found in the dev branch of the ratcave organization's repo, where active development is ongoing to add features and maintain backwards compatibility.

Could you please try installing that and let me know if it works for you?  You can install it by typing the following into the terminal:

```bash
pip install https://github.com/ratcave/ratcave/archive/dev.zip
```

**Comment by kabukunz** [comment] 2018-06-07 10:27
Hello there
Thank you for your quick feedback
On installing the new version, and running the base example
http://ratcave.readthedocs.io/en/latest/tutorial1.html#summary, I get:

Traceback (most recent call last):
  File "rtc.py", line 28, in <module>
    pyglet.app.run()
  File
"/Users/max/.pyenv/versions/3.5.3_Default/lib/python3.5/site-packages/pyglet/app/__init__.py",
line 138, in run
    event_loop.run()
  File
"/Users/max/.pyenv/versions/3.5.3_Default/lib/python3.5/site-packages/pyglet/app/base.py",
line 142, in run
    self._run()
  File
"/Users/max/.pyenv/versions/3.5.3_Default/lib/python3.5/site-packages/pyglet/app/base.py",
line 154, in _run
    timeout = self.idle()
  File
"/Users/max/.pyenv/versions/3.5.3_Default/lib/python3.5/site-packages/pyglet/app/base.py",
line 281, in idle
    window.dispatch_event('on_draw')
  File
"/Users/max/.pyenv/versions/3.5.3_Default/lib/python3.5/site-packages/pyglet/window/__init__.py",
line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File
"/Users/max/.pyenv/versions/3.5.3_Default/lib/python3.5/site-packages/pyglet/event.py",
line 357, in dispatch_event
    if handler(*args):
  File "rtc.py", line 26, in on_draw
    scene.draw()
  File
"/Users/max/.pyenv/versions/3.5.3_Default/lib/python3.5/site-packages/ratcave/scene.py",
line 38, in draw
    mesh.draw()
  File
"/Users/max/.pyenv/versions/3.5.3_Default/lib/python3.5/site-packages/ratcave/mesh.py",
line 185, in draw
    self.vao = VAO(indices=self.array_indices)
  File
"/Users/max/.pyenv/versions/3.5.3_Default/lib/python3.5/site-packages/ratcave/vertex.py",
line 25, in __init__
    self.id = create_opengl_object(gl.glGenVertexArrays)
  File
"/Users/max/.pyenv/versions/3.5.3_Default/lib/python3.5/site-packages/ratcave/utils/gl.py",
line 15, in create_opengl_object
    gl_gen_function(n, byref(handle))  # Create n Empty Objects
  File
"/Users/max/.pyenv/versions/3.5.3_Default/lib/python3.5/site-packages/pyglet/gl/lib.py",
line 105, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'

HTH

**Comment by nickdelgrosso** [comment] 2018-06-07 12:39
Hi,

Thank you for testing this!  I've hijacked a colleague's Mac and was able to reproduce the error you reported.  This also seems to be related to Apple's use of "Legacy Profile" OpenGL context by default.  Since Pyglet is the one creating the window (and, thus, the OpenGL context) , it's something that the Ratcave itself can't solve directly.  From my research, I see that the Pyglet developers have been working on it for a while: https://code.google.com/archive/p/pyglet/issues/532.  

I'm going to see if I can find some workarounds for Mac OS X this weekend.  In the meantime, we've been doing continuous integration testing with both Linux and Windows computers, and those platforms are working well.

**Comment by nickdelgrosso** [comment] 2018-06-07 13:50
Okay, it looks like I've found a fix! It turned out to be a simple process (for details on the solution, see pull request #31 ).  I've merged it in--could you please reinstall ratcave and test the tutorial again?

```
pip install https://github.com/ratcave/ratcave/archive/dev.zip
```

**Comment by kabukunz** [comment] 2018-06-07 14:16
Success! A monkey showed up on my screen.
Thank you for your support. I'm going to close the issue.
Kabu

**Closed** 2018-06-07 14:21 UTC

**Comment by nickdelgrosso** [comment] 2018-06-07 14:27
Yay!  Thank you for your quick feedback!
